"""
Module: Audit Report Generator
Description: Generates a professional PDF report of case calculations for compliance files.
"""

import fitz
import datetime
import os

class AuditGenerator:
    def __init__(self):
        pass

    def generate_report(self, case_data: dict, user_email: str) -> bytes:
        """
        Creates a PDF report for a single case record.
        Returns the PDF bytes.
        """
        doc = fitz.open()
        page = doc.new_page()
        
        # --- HEADER ---
        # Draw a header bar
        page.draw_rect(fitz.Rect(0, 0, 600, 80), color=(0.2, 0.2, 0.3), fill=(0.2, 0.2, 0.3))
        page.insert_text((30, 50), "LEGAL TOOLKIT: COMPLIANCE AUDIT", fontsize=20, fontname="helv", color=(1, 1, 1))
        
        # --- METADATA ---
        y = 120
        title = case_data.get('title', 'Untitled Matter')
        case_type = case_data.get('case_type', 'General').upper()
        date_created = case_data.get('created_at', datetime.datetime.now().isoformat())
        
        page.insert_text((30, y), f"Matter Reference: {title}", fontsize=14, fontname="helv")
        y += 25
        page.insert_text((30, y), f"Report Type:      {case_type} CALCULATION", fontsize=11, fontname="helv")
        y += 20
        page.insert_text((30, y), f"Generated By:     {user_email}", fontsize=11, fontname="helv")
        y += 20
        page.insert_text((30, y), f"Date Generated:   {datetime.datetime.now().strftime('%d %B %Y %H:%M')}", fontsize=11, fontname="helv")
        
        # --- DATA SECTION ---
        y += 50
        page.insert_text((30, y), "CALCULATION DETAILS", fontsize=12, fontname="helv", color=(0.2, 0.2, 0.6))
        page.draw_line(fitz.Point(30, y+5), fitz.Point(550, y+5))
        y += 30
        
        data = case_data.get('data', {})
        
        if case_type == "DEADLINE":
            self._render_deadline_data(page, data, y)
        elif case_type == "FEE":
            self._render_fee_data(page, data, y)
        else:
            page.insert_text((30, y), str(data), fontsize=10, fontname="helv")

        # --- FOOTER ---
        page.insert_text(
            (30, 800), 
            "This report is generated by Legal Toolkit for audit purposes. Confirm all dates with court orders.", 
            fontsize=8, 
            fontname="helv",
            color=(0.5, 0.5, 0.5)
        )

        return doc.tobytes()

    def _render_deadline_data(self, page, data, start_y):
        y = start_y
        
        items = [
            ("Date of Service", data.get('sent_at')),
            ("Jurisdiction", data.get('jurisdiction', 'England & Wales')),
            ("Deemed Service", data.get('deemed_service')),
            ("Standard Deadline", data.get('deadline')),
            ("Agreed Extension", f"{data.get('extension_days', 0)} Days")
        ]
        
        for label, value in items:
            if not value: continue
            # Format dates if they look like ISO strings
            if isinstance(value, str) and "T" in value:
                try:
                    dt = datetime.datetime.fromisoformat(value)
                    value = dt.strftime('%A, %d %B %Y')
                except:
                    pass
            
            page.insert_text((30, y), f"{label}:", fontsize=11, fontname="helv")
            page.insert_text((200, y), str(value), fontsize=11, fontname="helv")
            y += 25
            
    def _render_fee_data(self, page, data, start_y):
        y = start_y
        val = float(data.get('claim_value', 0))
        fee = float(data.get('fee', 0))
        
        page.insert_text((30, y), "Claim Value:", fontsize=11, fontname="helv")
        page.insert_text((200, y), f"£{val:,.2f}", fontsize=11, fontname="helv")
        y += 25
        
        page.insert_text((30, y), "Court Fee Payable:", fontsize=11, fontname="helv")
        page.insert_text((200, y), f"£{fee:,.2f}", fontsize=11, fontname="helv")
